Fix #105 - Update Readme
maykinmedia/record-management-app pull request #119
Opened 2021-01-26 08:29 UTC by SilviaAmAm

Fix #105

2021-01-26 13:59 UTC, joeribekker requested changes

2021-01-26 13:59 UTC, joeribekker commented on README.NL.rst
> +Copyright © Maykin Media, 2020
2021

2021-01-26 13:59 UTC, joeribekker commented on README.NL.rst
> +The RMA supports all backends implementing the 1.0.x `API's voor Zaakgericht Werken`_.
Archiefbeheer draait om het vernietigen van gegevens die aan het einde van hun levensduur zijn gekomen. Zaakgericht werken schrijft de archiveringsvoorwaarden voor, voor zaken die zijn beëindigd.

De Record Management App (RMA) biedt functionaliteit voor archiefbeheer om de vernietiging van zaken in te plannen
volgens de archiveringsvoorwaarden. De RMA volgt een proces dat uit meerdere stappen bestaat, over verschillende rollen.

Er is aandacht besteed aan de gebruikerservaring van de beheerders die de app gebruiken, met notificaties
om te informeren over lopende taken, volledige auditregistratie en traceerbaarheid van gebruiker- en
systeemacties.

De RMA ondersteunt alle backends die de 1.0.x  `API's voor Zaakgericht Werken`_ implementeren.

2021-01-27 16:16 UTC, annashamray requested changes
Could you also add

2021-01-27 16:16 UTC, annashamray commented on README.NL.rst
> +Zaakgericht record-management in het `Common Ground`_ landschap.
Could you also add badges to dutch README, please?

2021-01-27 16:16 UTC, annashamray commented on README.NL.rst
> +
I think quick-start section should also be here in case dutch speakers won't take a look at english README

2021-01-28 12:36 UTC, annashamray approved these changes

2021-01-28 12:38 UTC, merged